create table TBLPARTI(
ID INT IDENTITY(1,1) PRIMARY KEY,
ILCEAD NVARCHAR(40),
APARTI SMALLINT,
BPARTI SMALLINT,
CPARTI SMALLINT,
DPARTI SMALLINT,
EPARTI SMALLINT
)
go
insert into TBLPARTI (ILCEAD,APARTI,BPARTI,CPARTI,DPARTI,EPARTI) values ('ADALAR',10,20,30,40,50)
insert into TBLPARTI (ILCEAD,APARTI,BPARTI,CPARTI,DPARTI,EPARTI) values ('ARNAVUTKÖY',10,20,30,40,50) 
insert into TBLPARTI (ILCEAD,APARTI,BPARTI,CPARTI,DPARTI,EPARTI) values ('ŞİŞLİ',10,20,30,40,50) 
insert into TBLPARTI (ILCEAD,APARTI,BPARTI,CPARTI,DPARTI,EPARTI) values ('BAŞAKŞEHİR',10,20,30,40,50) 
insert into TBLPARTI (ILCEAD,APARTI,BPARTI,CPARTI,DPARTI,EPARTI) values ('ÜMRANİYE',10,20,30,40,50) 
insert into TBLPARTI (ILCEAD,APARTI,BPARTI,CPARTI,DPARTI,EPARTI) values ('TUZLA',10,20,30,40,50) 
insert into TBLPARTI (ILCEAD,APARTI,BPARTI,CPARTI,DPARTI,EPARTI) values ('ÜSKÜDAR',10,20,30,40,50)
